import "./globals.css";

export const metadata = {
  title: "Attendance tracker",
  description: "Generated by Technical Council",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
